services:
  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    ports: ["9000:9000", "9001:9001"]
    volumes: ["./minio_data:/data"]

  postgres:
    image: postgres:15
    container_name: local_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: demo_db
    ports: ["55432:5432"]
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgres_sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d demo_db"]
      interval: 5s
      retries: 10
      

  mysql:
    image: mysql:8.0
    container_name: local_mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: demo_db
    ports: ["5506:3306"]
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$MYSQL_ROOT_PASSWORD --silent"]
      interval: 5s
      retries: 10
      start_period: 20s

  trino:
    image: trinodb/trino:latest
    container_name: trino
    ports: ["8080:8080"]
    volumes:
      - ./trino/etc:/etc/trino
    depends_on:
      postgres:
        condition: service_healthy
      mysql:
        condition: service_healthy

volumes:
  pg_data:
  mysql_data:
